spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.188.14:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: myself
    password: myself
  redis:
    database: 3
    host: 192.168.188.14
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 30000
    timeout: -1
server:
  port: 8090
  context-path: /
